### ISSUE TITLE
Deprecated or not?

### ISSUE THREAD

**Issue by jasonkarns** [dchest/webp-quicklook#4]
The repo description says deprecated, but the repo is still active. Should it be archived?

Would also benefit from having a note in the readme that explains _why_ it is deprecated. Does macOS have native QL support for webp now?

**Comment by dchest** [comment]
It is deprecated, the notice was put there before GitHub implemented the archive option. I'm not sure if macOS natively supports webp, but I have a few image editors installed (Acorn, Pixelmator Pro and some other) and webp works with QuickLook for me.

It's deprecated because I'm not updating libwebp anymore, and it gained a few features, so newer files are not supported.
